
# https://forge.rust-lang.org/compiler/cross-compilation/windows.html

# [target.x86_64-pc-windows-msvc]
# linker = "lld-link"

# [target.aarch64-pc-windows-msvc]
# linker = "lld-link"

[target.aarch64-pc-windows-gnu]
linker = "lld-link"



[target.x86_64-apple-darwin]
linker = "rust-lld"

[target.aarch64-apple-darwin]
linker = "rust-lld"



[target.x86_64-unknown-linux-musl]
linker = "rust-lld"

[target.aarch64-unknown-linux-musl]
linker = "rust-lld"